cookbook 'rbenv', git: 'git://github.com/fnichol/chef-rbenv.git', :branch => 'v0.7.2'
cookbook 'ruby_build'
cookbook 'drupal', '~>1.2', github: 'promet/drupal_cookbook', branch: 'hotfix-web-app'
cookbook 'composer', '~>0.1', github: 'zircote/chef-composer'
cookbook 'promet_rsyslog', '=>0.2.1', github: 'promet/promet_rsyslog'
