---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.8.2
  customize:
    memory: 8192
    cpuexecutioncap: 100

platforms:
  - name: debian-7.2.0

suites:
  - name: deploy_pub_corp
    run_list:
      - recipe[test_cm22]
      - role[db_master]
      - recipe[drupal]
      - recipe[cm22]
    roles_path: test/fixtures/roles
    data_bags_path: test/fixtures/dbags
    attributes:
      mysql:
        server_debian_password: pass
        server_root_password: pass
        server_repl_password: pass
      cm22:
        machine_user: promet
        httpd_group: www-data
        webroot: /var/www/sites
        slave:
          base_data_bag_item: publication22cm
          sites:
            publication22cm: publication22cm
          process:
            - publication22cm
          git_ref: master
        master:
          sites:
            - corporate22cm
          process:
            - corporate22cm
          base_data_bag_item: corporate22cm
  - name: deploy_satellites
    run_list:
      - recipe[test_cm22]
      - role[db_master]
      - recipe[drupal]
      - recipe[cm22]
    roles_path: test/fixtures/roles
    data_bags_path: test/fixtures/dbags
    attributes:
      mysql:
        server_debian_password: pass
        server_root_password: pass
        server_repl_password: pass
      cm22:
        machine_user: promet
        webroot: /var/www/sites
        slave:
          process:
            - the_orland_park_prairie
            - the_frankfort_station
        master:
          base_data_bag_item: corporate22cm-staging
          process:
            - corporate22cm.prometstaging.com
  - name: some_vhosts
    run_list:
      - recipe[test_cm22]
      - role[db_master]
      - recipe[drupal]
      - recipe[cm22]
      - recipe[cm22::vhosts]
    roles_path: test/fixtures/roles
    data_bags_path: test/fixtures/dbags
    attributes:
      mysql:
        server_debian_password: pass
        server_root_password: pass
        server_repl_password: pass
      cm22:
        machine_user: promet
        webroot: /var/www/sites/twenty_second
        slave:
          process:
            - the_orland_park_prairie
            - the_frankfort_station
        master:
          base_data_bag_item: corporate22cm-staging
          process:
            - 22ndcenturymedia.com
