---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 8192
    cpuexecutioncap: 100

platforms:
  - name: debian-7.2.0

suites:
  - name: deploy_pub_corp
    run_list:
      - recipe[test_cm22]
      - role[db_master]
      - recipe[drupal]
      - recipe[cm22]
    roles_path: test/fixtures/roles
    data_bags_path: test/fixtures/dbags
    attributes:
      mysql:
        server_debian_password: pass
        server_root_password: pass
        server_repl_password: pass
      cm22:
        machine_user: promet
        httpd_group: www-data
        webroot: /var/www/sites
        slave:
          base_data_bag_item: publication22cm
          sites:
            publication22cm: publication22cm
          process:
            - publication22cm
          git_ref: settings-compile
          archive:
            source:
              https://s3-us-west-1.amazonaws.com/promet-22cm/archives/build/cm22slave_20140206-155028.tar.gz
        master:
          sites:
            - corporate22cm
          process:
            - corporate22cm
          git_ref: settings-compile
          base_data_bag_item: corporate22cm
          archive:
            source:
              https://s3-us-west-1.amazonaws.com/promet-22cm/archives/build/cm22master_20140206-172213.tar.gz
  - name: deploy_satellites
    run_list:
      - recipe[test_cm22]
      - role[db_master]
      - recipe[drupal]
      - recipe[cm22]
    roles_path: test/fixtures/roles
    data_bags_path: test/fixtures/dbags
    attributes:
      mysql:
        server_debian_password: pass
        server_root_password: pass
        server_repl_password: pass
      cm22:
        machine_user: promet
        webroot: /var/www/sites
        slave:
          process:
            - the_orland_park_prairie
            - the_frankfort_station
            - the_homer_horizon
            - the_lockport_legend
            - the_mokena_messenger
            - the_new_lenox_patriot
            - the_tinley_junction
            - the_glenview_lantern
            - the_northbrook_tower
            - the_wilmette_beacon
            - the_winnetka_current
            - malibu_surfside_news
          git_ref: settings-compile
          archive:
            source:
              https://s3-us-west-1.amazonaws.com/promet-22cm/archives/build/cm22slave_20140130-135157.tar.gz
        master:
          base_data_bag_item: corporate22cm-staging
          process:
            - corporate22cm.prometstaging.com
          git_ref: settings-compile
          archive:
            source:
              https://s3-us-west-1.amazonaws.com/promet-22cm/archives/build/cm22master_20140130-135502.tar.gz
