site :opscode

metadata
cookbook 'drupal', '~>1.2', github: 'promet/drupal_cookbook'
cookbook 'test_cm22', path: 'test/cookbooks/test_cm22'
cookbook 'users', path: '../users'
cookbook 'composer', github: 'zircote/chef-composer'
