# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "promet_wheezy"
  config.ssh.forward_agent = true
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe 'cm22'
    chef.json = {
      'cm22' => {
        'machine_user' => 'vagrant',
        'slave' => {
          'process' => [ 'publication22cm' ]
        },
        'master' => {
          'process' => [ 'corporate.prometstaging.com' ]
        }
      }
    }
  end
end
